modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/team-abnormals/boatload/issues"
license = "https://github.com/team-abnormals/boatload/blob/main/LICENSE.txt"

[[mods]]
    modId = "boatload"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "boatload:birch_furnace_boat"
    configBackground = "minecraft:textures/block/birch_planks.png"
    authors = "Team Abnormals"
    credits = "Markus1002, bageldotjpg"
    displayURL = "https://www.teamabnormals.com/mods/boatload"
    displayName = "Boatload"
    description = '''
    Adds Furnace Boats and Large Boats to make ocean exploration more interesting and interactive!
    '''

[[dependencies.boatload]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.boatload]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.boatload]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.0,)"
    ordering = "AFTER"
    side = "BOTH"